project_id: example
name: QA
description: 问答系统

common:
  source:
    repo: 

  api:
    base_url: 
    endpoint: 
    method: POST
    timeout: 10

  start:
    command: 
  
  ready: [output,reference]

extra: {}
